# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.10.3 on 2016-11-25 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=150)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='IntentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intent.Intent')),
            ],
        ),
    ]
