# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentdata',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
