# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.9.6 on 2016-11-11 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=150)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='DomainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Domain')),
            ],
        ),
    ]
